#pragma once

#define IDR_FONT_AWESOME_SOLID 201
#define IDR_FONT_INTER_SEMIBOLD 202
#define IDR_FONT_POPPINS_SEMIBOLD 203
#define IDR_FONT_POPPINS_BOLD 204
#define IDR_FONT_INTER_BOLD 205
#define IDR_FONT_MINECRAFT 206
#define IDR_FONT_CALIBRI_BOLD 207
#define IDR_FONT_KAMERIK  107
